// Code generated by protoc-gen-go.
// source: ims.proto
// DO NOT EDIT!

/*
Package ims is a generated protocol buffer package.

It is generated from these files:
	ims.proto

It has these top-level messages:
	Void
	StatusReply
	StopReply
	AssumeRoleRequest
	Profile
	ConfigReply
*/
package ims

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusReply struct {
	Error           string `protobuf:"bytes,1,opt,name=Error,json=error" json:"Error,omitempty"`
	Role            string `protobuf:"bytes,2,opt,name=Role,json=role" json:"Role,omitempty"`
	AccessKeyId     string `protobuf:"bytes,3,opt,name=AccessKeyId,json=accessKeyId" json:"AccessKeyId,omitempty"`
	SecretAccessKey string `protobuf:"bytes,4,opt,name=SecretAccessKey,json=secretAccessKey" json:"SecretAccessKey,omitempty"`
	SessionToken    string `protobuf:"bytes,5,opt,name=SessionToken,json=sessionToken" json:"SessionToken,omitempty"`
	Expiration      string `protobuf:"bytes,6,opt,name=Expiration,json=expiration" json:"Expiration,omitempty"`
}

func (m *StatusReply) Reset()                    { *m = StatusReply{} }
func (m *StatusReply) String() string            { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()               {}
func (*StatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StopReply struct {
	Error string `protobuf:"bytes,1,opt,name=Error,json=error" json:"Error,omitempty"`
}

func (m *StopReply) Reset()                    { *m = StopReply{} }
func (m *StopReply) String() string            { return proto.CompactTextString(m) }
func (*StopReply) ProtoMessage()               {}
func (*StopReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AssumeRoleRequest struct {
	Name string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Mfa  string `protobuf:"bytes,2,opt,name=Mfa,json=mfa" json:"Mfa,omitempty"`
}

func (m *AssumeRoleRequest) Reset()                    { *m = AssumeRoleRequest{} }
func (m *AssumeRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*AssumeRoleRequest) ProtoMessage()               {}
func (*AssumeRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Profile struct {
	AwsAccessKeyID     string `protobuf:"bytes,1,opt,name=AwsAccessKeyID,json=awsAccessKeyID" json:"AwsAccessKeyID,omitempty"`
	AwsSecretAccessKey string `protobuf:"bytes,2,opt,name=AwsSecretAccessKey,json=awsSecretAccessKey" json:"AwsSecretAccessKey,omitempty"`
	AwsSessionToken    string `protobuf:"bytes,3,opt,name=AwsSessionToken,json=awsSessionToken" json:"AwsSessionToken,omitempty"`
	Region             string `protobuf:"bytes,4,opt,name=Region,json=region" json:"Region,omitempty"`
	MFASerial          string `protobuf:"bytes,5,opt,name=MFASerial,json=mFASerial" json:"MFASerial,omitempty"`
	RoleARN            string `protobuf:"bytes,6,opt,name=RoleARN,json=roleARN" json:"RoleARN,omitempty"`
	SourceProfile      string `protobuf:"bytes,7,opt,name=SourceProfile,json=sourceProfile" json:"SourceProfile,omitempty"`
	RoleSessionName    string `protobuf:"bytes,8,opt,name=RoleSessionName,json=roleSessionName" json:"RoleSessionName,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ConfigReply struct {
	Profiles map[string]*Profile `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ConfigReply) Reset()                    { *m = ConfigReply{} }
func (m *ConfigReply) String() string            { return proto.CompactTextString(m) }
func (*ConfigReply) ProtoMessage()               {}
func (*ConfigReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ConfigReply) GetProfiles() map[string]*Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*Void)(nil), "ims.Void")
	proto.RegisterType((*StatusReply)(nil), "ims.StatusReply")
	proto.RegisterType((*StopReply)(nil), "ims.StopReply")
	proto.RegisterType((*AssumeRoleRequest)(nil), "ims.AssumeRoleRequest")
	proto.RegisterType((*Profile)(nil), "ims.Profile")
	proto.RegisterType((*ConfigReply)(nil), "ims.ConfigReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for InstanceMetaService service

type InstanceMetaServiceClient interface {
	Status(ctx context.Context, in *Void, opts ...grpc.CallOption) (*StatusReply, error)
	Stop(ctx context.Context, in *Void, opts ...grpc.CallOption) (*StopReply, error)
	AssumeRole(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*StatusReply, error)
	RetrieveRole(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*StatusReply, error)
	Config(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ConfigReply, error)
	SetCredentials(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type instanceMetaServiceClient struct {
	cc *grpc.ClientConn
}

func NewInstanceMetaServiceClient(cc *grpc.ClientConn) InstanceMetaServiceClient {
	return &instanceMetaServiceClient{cc}
}

func (c *instanceMetaServiceClient) Status(ctx context.Context, in *Void, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := grpc.Invoke(ctx, "/ims.InstanceMetaService/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceMetaServiceClient) Stop(ctx context.Context, in *Void, opts ...grpc.CallOption) (*StopReply, error) {
	out := new(StopReply)
	err := grpc.Invoke(ctx, "/ims.InstanceMetaService/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceMetaServiceClient) AssumeRole(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := grpc.Invoke(ctx, "/ims.InstanceMetaService/AssumeRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceMetaServiceClient) RetrieveRole(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := grpc.Invoke(ctx, "/ims.InstanceMetaService/RetrieveRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceMetaServiceClient) Config(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ConfigReply, error) {
	out := new(ConfigReply)
	err := grpc.Invoke(ctx, "/ims.InstanceMetaService/Config", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceMetaServiceClient) SetCredentials(ctx context.Context, in *AssumeRoleRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := grpc.Invoke(ctx, "/ims.InstanceMetaService/SetCredentials", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InstanceMetaService service

type InstanceMetaServiceServer interface {
	Status(context.Context, *Void) (*StatusReply, error)
	Stop(context.Context, *Void) (*StopReply, error)
	AssumeRole(context.Context, *AssumeRoleRequest) (*StatusReply, error)
	RetrieveRole(context.Context, *AssumeRoleRequest) (*StatusReply, error)
	Config(context.Context, *Void) (*ConfigReply, error)
	SetCredentials(context.Context, *AssumeRoleRequest) (*StatusReply, error)
}

func RegisterInstanceMetaServiceServer(s *grpc.Server, srv InstanceMetaServiceServer) {
	s.RegisterService(&_InstanceMetaService_serviceDesc, srv)
}

func _InstanceMetaService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(InstanceMetaServiceServer).Status(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _InstanceMetaService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(InstanceMetaServiceServer).Stop(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _InstanceMetaService_AssumeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AssumeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(InstanceMetaServiceServer).AssumeRole(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _InstanceMetaService_RetrieveRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AssumeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(InstanceMetaServiceServer).RetrieveRole(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _InstanceMetaService_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(InstanceMetaServiceServer).Config(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _InstanceMetaService_SetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AssumeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(InstanceMetaServiceServer).SetCredentials(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _InstanceMetaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ims.InstanceMetaService",
	HandlerType: (*InstanceMetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _InstanceMetaService_Status_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _InstanceMetaService_Stop_Handler,
		},
		{
			MethodName: "AssumeRole",
			Handler:    _InstanceMetaService_AssumeRole_Handler,
		},
		{
			MethodName: "RetrieveRole",
			Handler:    _InstanceMetaService_RetrieveRole_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _InstanceMetaService_Config_Handler,
		},
		{
			MethodName: "SetCredentials",
			Handler:    _InstanceMetaService_SetCredentials_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0x15, 0x5a, 0xca, 0xf6, 0xc2, 0xc2, 0x3a, 0x9a, 0x4d, 0xb3, 0x31, 0x9b, 0xb5, 0x1a, 0xe5,
	0x89, 0x07, 0x7c, 0x59, 0x89, 0x2f, 0xb8, 0x62, 0x42, 0x0c, 0x1b, 0xd3, 0x1a, 0xdf, 0xc7, 0x72,
	0xd9, 0x34, 0x0b, 0x1d, 0x9c, 0x19, 0x50, 0xfe, 0x87, 0xbf, 0xc0, 0x57, 0xff, 0x84, 0x6f, 0xfe,
	0x2d, 0xe7, 0x4b, 0x68, 0xc5, 0x98, 0xec, 0xdb, 0x9d, 0x73, 0xcf, 0x9d, 0xce, 0x39, 0x73, 0xa6,
	0x10, 0xe6, 0x4b, 0xd1, 0x5f, 0x71, 0x26, 0x19, 0xf1, 0x54, 0x19, 0x07, 0xe0, 0x7f, 0x64, 0xf9,
	0x2c, 0xfe, 0x55, 0x83, 0x56, 0x2a, 0xa9, 0x5c, 0x8b, 0x04, 0x57, 0x8b, 0x2d, 0x79, 0x08, 0x8d,
	0x31, 0xe7, 0x8c, 0x47, 0xb5, 0x8b, 0x5a, 0x2f, 0x4c, 0x1a, 0xa8, 0x17, 0x84, 0x80, 0x9f, 0xb0,
	0x05, 0x46, 0x75, 0x03, 0xfa, 0x5c, 0xd5, 0xe4, 0x02, 0x5a, 0xa3, 0x2c, 0x43, 0x21, 0xde, 0xe1,
	0x76, 0x32, 0x8b, 0x3c, 0xd3, 0x6a, 0xd1, 0x3d, 0x44, 0x7a, 0xd0, 0x4d, 0x31, 0xe3, 0x28, 0x77,
	0xbc, 0xc8, 0x37, 0xac, 0xae, 0xa8, 0xc2, 0x24, 0x86, 0x76, 0xaa, 0xca, 0x9c, 0x15, 0x1f, 0xd8,
	0x2d, 0x16, 0x51, 0xc3, 0xd0, 0xda, 0xa2, 0x84, 0x91, 0x73, 0x80, 0xf1, 0xd7, 0x55, 0xce, 0xa9,
	0x54, 0x50, 0x14, 0x18, 0x06, 0xe0, 0x0e, 0x89, 0x1f, 0x43, 0x98, 0x4a, 0xb6, 0xfa, 0x8f, 0x8c,
	0xf8, 0x25, 0xdc, 0x1f, 0x09, 0xb1, 0x5e, 0xa2, 0x16, 0x93, 0xe0, 0xe7, 0x35, 0x0a, 0xa9, 0xb5,
	0x5d, 0xd3, 0x25, 0x3a, 0xa6, 0x5f, 0xa8, 0x9a, 0x9c, 0x80, 0x37, 0x9d, 0x53, 0x27, 0xd7, 0x5b,
	0xce, 0x69, 0xfc, 0xa3, 0x0e, 0xcd, 0xf7, 0x9c, 0xcd, 0x73, 0xa5, 0xfc, 0x19, 0x74, 0x46, 0x5f,
	0xc4, 0x5e, 0xfc, 0x1b, 0x37, 0xdb, 0xa1, 0x15, 0x94, 0xf4, 0x81, 0x28, 0xde, 0xdf, 0x16, 0xd8,
	0x4d, 0x09, 0x3d, 0xe8, 0x68, 0xbf, 0x0c, 0xbf, 0x64, 0x84, 0x75, 0xb5, 0x4b, 0xab, 0x30, 0x39,
	0x85, 0x20, 0xc1, 0x1b, 0xed, 0x83, 0x35, 0x34, 0xe0, 0x66, 0x45, 0x1e, 0x41, 0x38, 0x7d, 0x3b,
	0x4a, 0x91, 0xe7, 0x74, 0xe1, 0x4c, 0x0c, 0x97, 0x7f, 0x00, 0x12, 0x41, 0x53, 0x0b, 0x1f, 0x25,
	0xd7, 0xce, 0xbe, 0x26, 0xb7, 0x4b, 0xf2, 0x14, 0x8e, 0x53, 0xb6, 0xe6, 0x19, 0x3a, 0x89, 0x51,
	0xd3, 0xf4, 0x8f, 0x45, 0x19, 0xd4, 0xe7, 0xd3, 0xf3, 0xee, 0x24, 0xc6, 0xb4, 0x23, 0x7b, 0x3e,
	0x5e, 0x85, 0xe3, 0x6f, 0x2a, 0x55, 0x57, 0xac, 0x98, 0xe7, 0x37, 0xf6, 0x3a, 0x86, 0x70, 0xb4,
	0xb2, 0x9b, 0x08, 0xe5, 0x95, 0xd7, 0x6b, 0x0d, 0xce, 0xfb, 0x3a, 0x90, 0x25, 0x4e, 0xdf, 0x7d,
	0x45, 0x8c, 0x0b, 0xc9, 0xb7, 0xc9, 0x8e, 0x7f, 0x36, 0x81, 0xe3, 0x4a, 0x4b, 0x5f, 0xce, 0xad,
	0xf2, 0xd1, 0x7a, 0xae, 0x4b, 0x15, 0x9f, 0xc6, 0x86, 0x2e, 0xd6, 0x36, 0x9f, 0xad, 0x41, 0xdb,
	0xec, 0xed, 0x86, 0x12, 0xdb, 0x1a, 0xd6, 0x2f, 0x6b, 0x83, 0x9f, 0x75, 0x78, 0x30, 0x29, 0x84,
	0xa4, 0x45, 0x86, 0x53, 0x94, 0x54, 0xf9, 0xb2, 0xc9, 0x33, 0x24, 0xcf, 0x21, 0xb0, 0x6f, 0x80,
	0x84, 0x66, 0x54, 0xbf, 0x8c, 0xb3, 0x13, 0x53, 0x96, 0xde, 0x46, 0x7c, 0x8f, 0x3c, 0x01, 0x5f,
	0x67, 0xac, 0x4c, 0xeb, 0x38, 0x9a, 0x4b, 0x9e, 0x22, 0x5d, 0x02, 0xec, 0x53, 0x46, 0x4e, 0x4d,
	0xff, 0x20, 0x76, 0xff, 0xdc, 0x7e, 0x08, 0xed, 0x04, 0x25, 0xcf, 0x71, 0x73, 0xf7, 0x59, 0xa5,
	0xc1, 0xba, 0x79, 0xa8, 0xa1, 0xe4, 0xb2, 0x22, 0xbe, 0x82, 0x4e, 0x8a, 0xf2, 0x8a, 0xe3, 0x0c,
	0x0b, 0xa9, 0x62, 0x21, 0xee, 0xf2, 0x99, 0xd7, 0xc1, 0xf7, 0xba, 0x37, 0x99, 0xa6, 0x9f, 0x02,
	0xf3, 0x2f, 0x79, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x47, 0x82, 0x15, 0x58, 0x04, 0x00,
	0x00,
}
